/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: '#0A0A0A',
                foreground: '#FAFAFA',
                muted: '#1A1A1A',
                mutedForeground: '#737373',
                accent: '#FF3D00',
                accentForeground: '#0A0A0A',
                border: '#262626',
                input: '#1A1A1A',
                card: '#0F0F0F',
                cardForeground: '#FAFAFA',
                ring: '#FF3D00',
                hover: '#333333',
            },
            fontFamily: {
                sans: ['"Inter Tight"', '"Inter"', 'system-ui', 'sans-serif'],
                display: ['"Playfair Display"', 'Georgia', 'serif'],
                mono: ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
            },
            fontSize: {
                'xs': '0.75rem',
                'sm': '0.875rem',
                'base': '1rem',
                'lg': '1.125rem',
                'xl': '1.25rem',
                '2xl': '1.5rem',
                '3xl': '2rem',
                '4xl': '2.5rem',
                '5xl': '3.5rem',
                '6xl': '4.5rem',
                '7xl': '6rem',
                '8xl': '8rem',
                '9xl': '10rem',
            },
            letterSpacing: {
                'tighter': '-0.06em',
                'tight': '-0.04em',
                'normal': '-0.01em',
                'wide': '0.05em',
                'wider': '0.1em',
                'widest': '0.2em',
            },
            lineHeight: {
                'none': '1',
                'tight': '1.1',
                'snug': '1.25',
                'normal': '1.6',
                'relaxed': '1.75',
            },
            borderRadius: {
                DEFAULT: '0px',
                'none': '0px',
                'sm': '0px',
                'md': '0px',
                'lg': '0px',
                'xl': '0px',
                '2xl': '0px',
                '3xl': '0px',
                'full': '0px',
            },
            borderWidth: {
                DEFAULT: '1px',
                'thick': '2px',
            },
            boxShadow: {
                DEFAULT: 'none',
                'sm': 'none',
                'md': 'none',
                'lg': 'none',
                'xl': 'none',
                '2xl': 'none',
                'inner': 'none',
            },
            dropShadow: {
                DEFAULT: 'none',
                'sm': 'none',
                'md': 'none',
                'lg': 'none',
                'xl': 'none',
                '2xl': 'none',
            },
            transitionDuration: {
                'superfast': '150ms',
                'fast': '200ms',
                'normal': '500ms',
            },
            transitionTimingFunction: {
                'confident': 'cubic-bezier(0.25, 0, 0, 1)',
            }
        },
    },
    plugins: [],
}
